INSERT INTO CLIENT (NOM_CLIENT, COGNOM_CLIENT, DATA) VALUES ('Joan', 'Petit', '2020-12-21');
INSERT INTO CLIENT (NOM_CLIENT, COGNOM_CLIENT, DATA) VALUES ('Joana', 'Petita', '2021-12-21');
INSERT INTO CLIENT (NOM_CLIENT, COGNOM_CLIENT, DATA) VALUES ('Gegant', 'Nobita', '2020-12-01');