INSERT INTO ALUMNE (NOM_ALUMNE, COGNOM_ALUMNE, DATA) VALUES ('Joan', 'Petit', '2020-12-21');
INSERT INTO ALUMNE (NOM_ALUMNE, COGNOM_ALUMNE, DATA) VALUES ('Joana', 'Petita', '2021-12-21');
INSERT INTO ALUMNE (NOM_ALUMNE, COGNOM_ALUMNE, DATA) VALUES ('Gegant', 'Nobita', '2020-12-01');